### ISSUE TITLE
Middleware doesn't call close() on iterable properly.

### ISSUE THREAD

**Issue by GrahamDumpleton** [paylogic/wsgi-statsd#2] opened 2015-01-14 20:28 UTC
Your solution to timing when generator returned doesn't ensure that close() is called on iterable properly. This can result in resource cleanup not being performed properly. Read:

* http://blog.dscpl.com.au/2012/10/obligations-for-calling-close-on.html

It also will not work in general where an exception is raised when pulling items from the iterable.

I did say it isn't simple to get this all right. :-)

**Comment by bubenkoff** [comment] 2015-01-14 20:51
the cases when exception is raised are NOT measured intentionally - that's
by design
the idea is that those when exception happened should be addressed by
different service (for example - sentry) and it makes not much sense to
measure them as it's an Exception.
About the close - this is very useful, thanks!

On 14 January 2015 at 21:28, Graham Dumpleton <notifications@github.com>
wrote:

> Your solution to timing when generator returned doesn't ensure that
> close() is called on iterable properly. This can result in resource cleanup
> not being performed properly. Read:
>
>    -
>    http://blog.dscpl.com.au/2012/10/obligations-for-calling-close-on.html
>
> It also will not work in general where an exception is raised when pulling
> items from the iterable.
>
> I did say it isn't simple to get this all right. :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paylogic/wsgi-statsd/issues/2>.
>



-- 
Anatoly Bubenkov

**Comment by GrahamDumpleton** [comment] 2015-01-14 21:16
From experience we have seen from customer cases where when exceptions occur the response time can be quite large. This can be significant because it affects server capacity as that request thread is still going to be busy and and unavailable for handling requests. Ignoring it entirely is not necessarily a good idea. Measurement of them can still be worthwhile independent of capturing exception details.

**Comment by bubenkoff** [comment] 2015-01-14 21:22
totally agree about the response time
about the measurement-anyway: i think it can be a setting with a default False

**Comment by bubenkoff** [comment] 2015-01-14 21:22
in our situation we didn't want to measure exceptions, at least for now as it will only make stats processing more difficult

**Comment by GrahamDumpleton** [comment] 2015-01-14 21:25
Anyway, here is an actual case study of where tracking error response can be important.

* http://blog.newrelic.com/2011/11/02/monitoring-python-on-django-optimizing-for-page-not-found/

In that case the exception is swallowed by Django and so a normal response is still seen by the WSGI middleware doing timing, but same type of issue.

This highlights another thing. Most frameworks will swallow exceptions and convert them to error pages, so your idea for ignoring exceptions that get to top level and ignore then usually isn't going to work.

**Comment by bubenkoff** [comment] 2015-01-14 22:28
i solved both issues raised here

**Comment by GrahamDumpleton** [comment] 2015-01-14 23:08
You aren't calling close() when an exception occurs. That was the whole point of what the blog post was saying people do wrong. The close() call should be done in a finally clause around just the consumption of the iterable. Check the blog post again.

**Comment by bubenkoff** [comment] 2015-01-15 00:11
thanks!
i had that variant but then replaced it again
Now it should be good

**Comment by GrahamDumpleton** [comment] 2015-01-15 01:28
That looks good at this point. Will create separate issue for next problem. :-)

**Comment by bubenkoff** [comment] 2015-01-15 01:29
thanks a lot for the contribution!

**Closed by bubenkoff** 2015-01-15 01:29 UTC
